services:
  postgres:
    container_name: postgress
    image: postgres:17 # Nota: L'ultima versione stabile è postgres:16. La 17 è in beta.
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  springboot-app:
    restart: always
    container_name: springboot-app
    build:
      context: ./energycommunities  # <--- MODIFICATO
      dockerfile: Dockerfile      # Ora Docker lo troverà dentro 'energycommunities'
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  angular-app:
    container_name: angular-app
    build:
      context: ./energycommunities-ng # Questo è già corretto
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - springboot-app

volumes:
  postgres-data: