services:
  postgres:
    container_name: postgress
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./VOLUMES/postgres-data:/var/lib/postgresql/data
  
  springboot-app:
    restart: always
    container_name: springboot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  
  angular-app:
    container_name: angular-app
    build:
      context: ./energycommunities-ng
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - springboot-app