# =========================
# Configurazione SonarCloud
# =========================

# Chiave del progetto
sonar.projectKey=GiuseppeRudi_PowerHive-Energy-Communities
sonar.organization=giusepperudi

# Informazioni globali
sonar.projectName=PowerHive Energy Communities
sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarcloud.io

# Elenco dei moduli
sonar.modules=backend,frontend

# =======================================
# --- Configurazione del Modulo BACKEND ---
# =======================================
backend.sonar.projectName=Backend (Java)
backend.sonar.projectBaseDir=energycommunities
backend.sonar.sources=src/main/java
backend.sonar.tests=src/test/java
backend.sonar.java.binaries=target/classes

# ❌ Disattiva completamente la coverage
backend.sonar.coverage.exclusions=**

# ========================================
# --- Configurazione del Modulo FRONTEND ---
# ========================================
frontend.sonar.projectName=Frontend (Angular)
frontend.sonar.projectBaseDir=energycommunities-ng
frontend.sonar.sources=src
frontend.sonar.tests=src
frontend.sonar.test.inclusions=**/*.spec.ts
frontend.sonar.exclusions=node_modules/

# ❌ Disattiva completamente la coverage
frontend.sonar.coverage.exclusions=**