# Chiave del progetto (presa dalla tua schermata)
sonar.projectKey=GiuseppeRudi_PowerHive-Energy-Communities
sonar.organization=giusepperudi

# Informazioni globali
sonar.projectName=PowerHive Energy Communities
sonar.sourceEncoding=UTF-8

# Elenco dei "moduli" (le tue due applicazioni)
sonar.modules=backend,frontend

# --- Configurazione del Modulo BACKEND ---
sonar.backend.sonar.projectName=Backend (Java)
sonar.backend.sonar.projectBaseDir=energycommunities
sonar.backend.sonar.sources=src/main/java
sonar.backend.sonar.tests=src/test/java
sonar.backend.sonar.java.binaries=target/classes

# --- Configurazione del Modulo FRONTEND ---
sonar.frontend.sonar.projectName=Frontend (Angular)
sonar.frontend.sonar.projectBaseDir=energycommunities-ng
sonar.frontend.sonar.sources=src
sonar.frontend.sonar.tests=src
sonar.frontend.sonar.test.inclusions=**/*.spec.ts
sonar.frontend.sonar.exclusions=node_modules/
sonar.frontend.sonar.typescript.lcov.reportPaths=coverage/lcov.info